FROM alexisespinosa/ubuntu1604-mpich314-of1606

#---------------------------------------------------------------
#---------------------------------------------------------------
#---------------------------------------------------------------
#Settings for using openfoam with host mpi (in Pawsey)
USER root

#From the prefs.sh settings that have been used for installing openfoam above
ENV WM_MPLIB=SYSTEMMPI
ENV MPI_ROOT="/usr"
ENV MPI_ARCH_FLAGS="-DMPICH_SKIP_MPICXX"
ENV MPI_ARCH_INC="-isystem ${MPI_ROOT}/include"
ENV MPI_ARCH_LIBS="-L${MPI_ROOT}/lib -lmpich"

#From the etc/bashrc file that is usually sourced for openfoam to work
ENV WM_PROJECT=OpenFOAM
ENV WM_PROJECT_VERSION=v1606+
ENV FOAM_INST_DIR="/home/ofuser/${WM_PROJECT}"
ENV WM_COMPILER_TYPE=system
ENV WM_COMPILER=Gcc
ENV WM_ARCH_OPTION=64
ENV WM_PRECISION_OPTION=DP
ENV WM_LABEL_SIZE=32
ENV WM_COMPILE_OPTION=Opt
#ENV WM_MPLIB=SYSTEMMPI
ENV WM_OSTYPE=POSIX
ENV WM_PROJECT_INST_DIR=$FOAM_INST_DIR
ENV WM_PROJECT_DIR=$WM_PROJECT_INST_DIR/$WM_PROJECT-$WM_PROJECT_VERSION
ENV WM_THIRD_PARTY_DIR=$WM_PROJECT_INST_DIR/ThirdParty-$WM_PROJECT_VERSION
ENV WM_PROJECT_USER_DIR=$HOME/$WM_PROJECT/$USER-$WM_PROJECT_VERSION
ENV FOAM_SETTINGS="$@"

#Even if it looks dirty(and repeating), Im Hardcoding from a fully set environment container with ofv1606+ for testing
#Will clean later to make it work properly for other versions
ENV WM_LINK_LANGUAGE=c++
ENV FOAM_SOLVERS=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/applications/solvers
ENV FOAM_EXT_LIBBIN=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64GccDPInt32Opt/lib
ENV FOAM_APPBIN=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/bin
ENV FOAM_TUTORIALS=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/tutorials
ENV FOAM_JOB_DIR=/home/ofuser/OpenFOAM/jobControl
ENV WM_ARCH=linux64
ENV WM_COMPILER_TYPE=system
ENV WM_OSTYPE=POSIX
ENV MPI_ARCH_PATH=/usr
ENV WM_THIRD_PARTY_DIR=/home/ofuser/OpenFOAM/ThirdParty-v1606+
ENV CGAL_ARCH_PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/CGAL-4.8
ENV FOAM_SITE_APPBIN=/home/ofuser/OpenFOAM/site/v1606+/platforms/linux64GccDPInt32Opt/bin
ENV SCOTCH_ARCH_PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64GccInt32/scotch_6.0.3
ENV BOOST_ARCH_PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/boost_1_61_0
ENV FOAM_APP=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/applications
ENV WM_CXXFLAGS="-m64 -fPIC -std=c++0x"
ENV WM_CFLAGS="-m64 -fPIC"
ENV WM_PROJECT_VERSION=v1606+
ENV OAM_SITE_LIBBIN=/home/ofuser/OpenFOAM/site/v1606+/platforms/linux64GccDPInt32Opt/lib
ENV LD_LIBRARY_PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/fftw-3.3.4/lib64:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/CGAL-4.8/lib:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/boost_1_61_0/lib:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/gperftools-svn/lib:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/ParaView-5.0.1/lib/paraview-5.0:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/lib/mpi-system:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64GccDPInt32Opt/lib/mpi-system:/home/ofuser/OpenFOAM/ofuser-v1606+/platforms/linux64GccDPInt32Opt/lib:/home/ofuser/OpenFOAM/site/v1606+/platforms/linux64GccDPInt32Opt/lib:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/lib:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64GccDPInt32Opt/lib:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/lib/dummy
ENV MPI_BUFFER_SIZE=20000000
ENV WM_COMPILER_LIB_ARCH=64
ENV FOAM_SRC=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/src
ENV FOAM_SIGFPE=
ENV ParaView_DIR=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/ParaView-5.0.1
ENV WM_PROJECT_INST_DIR=/home/ofuser/OpenFOAM
ENV FOAM_UTILITIES=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/applications/utilities
ENV WM_CXX=g++
ENV WM_PROJECT_DIR=/home/ofuser/OpenFOAM/OpenFOAM-v1606+
ENV WM_LABEL_OPTION=Int32
ENV WM_PROJECT=OpenFOAM
ENV WM_LDFLAGS=-m64
ENV WM_COMPILER=Gcc
ENV PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/gperftools-svn/bin:/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/ParaView-5.0.1/bin:/home/ofuser/OpenFOAM/ofuser-v1606+/platforms/linux64GccDPInt32Opt/bin:/home/ofuser/OpenFOAM/site/v1606+/platforms/linux64GccDPInt32Opt/bin:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/bin:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/bin:/home/ofuser/OpenFOAM/OpenFOAM-v1606+/wmake:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH
ENV WM_MPLIB=SYSTEMMPI
ENV FOAM_USER_LIBBIN=/home/ofuser/OpenFOAM/ofuser-v1606+/platforms/linux64GccDPInt32Opt/lib
#ENV MPI_ARCH_LIBS="-L/usr/lib -lmpich"
ENV WM_CC=gcc
ENV FOAM_ETC=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/etc
ENV PV_PLUGIN_PATH=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/lib/paraview-5.0
ENV FOAM_INST_DIR=/home/ofuser/OpenFOAM
ENV ParaView_INCLUDE_DIR=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/ParaView-5.0.1/include/paraview-5.0
ENV FOAM_MPI=mpi-system
ENV FOAM_LIBBIN=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/platforms/linux64GccDPInt32Opt/lib
ENV WM_COMPILE_OPTION=Opt
ENV ParaView_VERSION=5.0.1
ENV WM_DIR=/home/ofuser/OpenFOAM/OpenFOAM-v1606+/wmake
ENV WM_LABEL_SIZE=32
ENV ParaView_MAJOR=5.0
ENV FOAM_SETTINGS=
#ENV MPI_ARCH_INC="-isystem /usr/include"
ENV MPI_ROOT=/usr
#ENV MPI_ARCH_FLAGS="-DMPICH_SKIP_MPICXX"
ENV WM_PROJECT_USER_DIR=/home/ofuser/OpenFOAM/ofuser-v1606+
ENV FOAM_RUN=/home/ofuser/OpenFOAM/ofuser-v1606+/run
ENV WM_OPTIONS=linux64GccDPInt32Opt
ENV WM_PRECISION_OPTION=DP
ENV FFTW_ARCH_PATH=/home/ofuser/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/fftw-3.3.4
ENV WM_ARCH_OPTION=64
ENV FOAM_USER_APPBIN=/home/ofuser/OpenFOAM/ofuser-v1606+/platforms/linux64GccDPInt32Opt/bin
ENV SCOTCH_VERSION=scotch_6.0.3
#---------------------------------------------------------------
#---------------------------------------------------------------
#---------------------------------------------------------------



